name: Deploy OG Images

on:
  push:
    branches:
      - master
    paths:
      - 'skybase/functions/og-images/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SKYBASE_ACCESS_TOKEN: ${{ secrets.SKYBASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.OG_IMAGE_SKYBASE_PROJECT_ID }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup the Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase functions deploy og-images --project-ref $PROJECT_ID --no-verify-jwt
